---
- name: Create Grafana directory
  file:
    path: /home/{{ default_user }}/{{ CONTAINER_NAME }}/
    state: directory
    mode: 0755
  tags:
  - asbrl-grafana

- name: Copy Grafana dashboards
  copy:
    src: ./files/
    dest: /home/{{ default_user }}/{{ CONTAINER_NAME }}
    mode: 0644
  tags:
  - asbrl-grafana

- name: Grafana config file
  template:
    src: grafana.ini.j2
    dest: /home/{{ default_user }}/{{ CONTAINER_NAME }}/grafana.ini
    mode: 0644
  tags:
  - asbrl-grafana

- name: Grafana config datasource file
  template:
    src: config-datasource.yml.j2
    dest: /home/{{ default_user }}/{{ CONTAINER_NAME }}/provisioning/config-datasource.yml
    mode: 0644
  tags:
  - asbrl-grafana

- name: Grafana config dashboard file
  template:
    src: config-dashboard.yml.j2
    dest: /home/{{ default_user }}/{{ CONTAINER_NAME }}/provisioning/config-dashboard.yml
    mode: 0644
  tags:
  - asbrl-grafana

- name: Grafana
  docker_container:
    name: "{{ CONTAINER_NAME }}"
    image: "{{ IMAGE }}:{{ BUILD }}"
    pull: "true"
    env:
      GF_INSTALL_PLUGINS: "{{ PLUGIN }}"
    cpu_period: "{{ DOCKER_CPU_PERIOD }}"
    cpu_quota: "{{ DOCKER_CPU_QUOTA }}"
    memory: "{{ DOCKER_MEMORY }}"
    state: "{{ CONTAINER_STATE }}"
    recreate: "yes"
    restart_policy: "unless-stopped"
    published_ports: "{{ DOCKER_PUBLISHED_PORTS | default(omit) }}"
    exposed_ports: "{{ DOCKER_EXPOSED_PORTS | default(omit) }}"
    volumes:
      - /home/{{ default_user }}/{{ CONTAINER_NAME }}/grafana.ini:/etc/grafana/grafana.ini
      - /home/{{ default_user }}/{{ CONTAINER_NAME }}/provisioning/dashboards/:/etc/grafana/provisioning/dashboards
      - /home/{{ default_user }}/{{ CONTAINER_NAME }}/provisioning/config-datasource.yml:/etc/grafana/provisioning/datasources/config-datasource.yml
      - /home/{{ default_user }}/{{ CONTAINER_NAME }}/provisioning/config-dashboard.yml:/etc/grafana/provisioning/dashboards/config-dashboard.yml
      # - grafana_data:/var/lib/grafana
    labels: "{{ DOCKER_LABELS | default(omit) }}"
  tags:
  - asbrl-grafana
