---
- name: Create Grafana directory
  file:
    path: /home/{{default_user}}/grafana/
    state: directory  

- name: Copy Grafana dashboards
  copy:
    src: ./files/
    dest: /home/{{default_user}}/grafana

- name: Grafana Data Volume
  docker_volume:
    name: grafana_data
    state: present

- name: Grafana config file
  template:
    src: grafana.ini.j2
    dest: /home/{{default_user}}/grafana/grafana.ini       

- name: Grafana config datasource file
  template:
    src: config-datasource.yml.j2
    dest: /home/{{default_user}}/grafana/provisioning/config-datasource.yml 

- name: Grafana config dashboard file
  template:
    src: config-dashboard.yml.j2
    dest: /home/{{default_user}}/grafana/provisioning/config-dashboard.yml

- name: Grafana
  docker_container:
    name: "grafana"
    image: "{{ IMAGE }}:{{ BUILD }}"
    pull: "true"
    env:
      GF_INSTALL_PLUGINS: "{{ PLUGIN }}"    
    recreate: "yes"
    state: "started"
    restart_policy: "unless-stopped"
    published_ports:
        - "0.0.0.0:3000:3000"
    volumes:
      - /home/{{default_user}}/grafana/grafana.ini:/etc/grafana/grafana.ini
      - /home/{{default_user}}/grafana/provisioning/dashboards/:/etc/grafana/provisioning/dashboards
      - /home/{{default_user}}/grafana/provisioning/config-datasource.yml:/etc/grafana/provisioning/datasources/config-datasource.yml
      - /home/{{default_user}}/grafana/provisioning/config-dashboard.yml:/etc/grafana/provisioning/dashboards/config-dashboard.yml
      - grafana_data:/var/lib/grafana
